name: CI

on: [push]

jobs:
  demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo test, ${{ secrets.GITHUB_TOKEN }}
    - name: Get Github User Info
      id: github_user_info
      uses: chandrakiran-dev/sfdx-actions/get-user-info@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
    - name: Print User
      run: | 
        echo test, ${{steps.github_user_info.outputs.OUTPUT_USER}}
        echo test, ${{ github.actor }}
      
      
