name: CI

on: [push]

jobs:
  demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo test, ${{ secrets.GITHUB_TOKEN }}
    - name: Get Github User Info
      id: github_user_info
      uses: chandrakiran-dev/sfdx-actions/get-user-info@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        USERNAME: ${{ github.actor }}
    - name: Get branch name
      id: get_branch_name
      uses: chandrakiran-dev/sfdx-actions/get-branch-name@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        USERNAME: ${{ github.actor }}
    - name: Print branch name
      run: echo Hello, world! ${{steps.get_branch_name.outputs.BRANCH_NAME}}
    #- name: Get Github User Info
    #  uses: peterjgrainger/action-create-branch@v2.0.1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #    branch: 'release-notes'
   

      

      
