name: CI

on: [push]

jobs:
  demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo test, ${{ secrets.GITHUB_TOKEN }}
    - name: Get Github User Info
      id: github_user_info
      if: steps.check.outputs.isMatch == 'true'
      shell: bash
      run: curl https://api.github.com/user
