name: CI

on: [push]

jobs:
  demo:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo test, ${{ secrets.GITHUB_TOKEN }}
    - name: Get Github User Info
      id: github_user_info
      uses: chandrakiran-dev/sfdx-actions/get-user-info@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        USERNAME: ${{ github.actor }}
    - name: Get Github User Info
      id: firebase_token
      uses: chandrakiran-dev/sfdx-actions/firebase-actions@master
      with:
        FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL}}
        FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
    - name: Stash credentials for later
      shell: bash
      run: |
          value=$(node scripts/extract-issue-number.js "https://api.github.com/repos/chandrakiran-dev/Salesforce-ci-cd/issues/3")
          curl -X PUT -d '"${value}"' https://salesforce-orgs-default-rtdb.firebaseio.com/${{ secrets.PROJECT_NAME }}-$value.json?access_token=${{ steps.firebase_token.outputs.ACCESS_TOKEN }}

      

      
