name: Push event feature branch

on:
  push:
    branches:
    - "feature/*"

jobs:
  Push-event-feature-branch:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Push-event-feature-branch
    - name: Populate auth file with SFDX_URL secret
      shell: bash
      run: echo ${{ secrets.UAT_ORG_SFDXURL }} > ./SFDX_UAT_URL_STORE.txt
    - name: Authenticate against UAT org
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:auth:sfdxurl:store --sfdxurlfile=./SFDX_UAT_URL_STORE.txt --setalias=uat-org
    - name: Verify the deployment
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:mdapi:deploy -d manifest/ -l RunLocalTests --targetusername=uat-org --checkonly --loglevel error
    - name: Display Report
      uses: forcedotcom/salesforcedx-actions@master
      with:
          args: force:source:deploy:report
    - name: Run a one-line script
      run: echo Run Completed

      

      
