name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run a one-line script
              run: echo ${{ github.event.changes.column_id.from }} to ${{ github.event.project_card.column_id }}
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
                echo test, ${{ secrets.GITHUB_TOKEN }}
            - name: Push source
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:source:push
            - name: Check move from "TO DO" to "IN PROGRESS"
              id: check
              uses: chandrakiran-dev/sfdx-actions/project_card-check-movement@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fromColumnId: ${{ github.event.changes.column_id.from }}
                  fromColumnName: TO DO
                  toColumnId: ${{ github.event.project_card.column_id }}
                  toColumnName: IN PROGRESS
            - name: Run a one-line script
              run: echo complted
            - name: Check out the source code
              if: steps.check.outputs.isMatch == 'true'
              run: echo success
    
