name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Run a one-line script
              run: echo ${{ github.event.changes.column_id.from }} to ${{ github.event.project_card.column_id }}
            - name: Run a multi-line script
              run: |
                echo Add other actions to build,
                echo test, and deploy your project.
                echo test, ${{ secrets.GITHUB_TOKEN }}
    
