name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check move from "TO DO" to "IN PROGRESS"
              id: check
              uses: chandrakiran-dev/sfdx-actions/project_card-check-movement@master
              with:
                  token: ${{ secrets.GITHUB_TOKEN}}
                  fromColumnId: ${{ github.event.changes.column_id.from }}
                  fromColumnName: TO DO
                  toColumnId: ${{ github.event.project_card.column_id }}
                  toColumnName: IN PROGRESS
            - name: Check out the source code
              uses: actions/checkout@v1
              if: steps.check.outputs.isMatch == 'true'
            - name: Print featue franch name
              if: steps.check.outputs.isMatch == 'true'
              shell: bash
              run: echo feature/${{ github.event.issue.number }} ${{ github.event.issue.title }}
            - name: Create new feature branch
              uses: peterjgrainger/action-create-branch@v2.0.1
              if: steps.check.outputs.isMatch == 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  branch: ${{ github.event.issue.number }} ${{ github.event.issue.title }}
            - name: Populate auth file with SFDX_URL secret
              if: steps.check.outputs.isMatch == 'true'
              shell: bash
              run: echo ${{ secrets.DEV_HUB_SFDXURL}} > ./SFDX_URL_STORE.txt
            - name: Authenticate against dev hub
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:auth:sfdxurl:store --sfdxurlfile=./SFDX_URL_STORE.txt --setalias=devhub --setdefaultdevhubusername
            - name: Create scratch org
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:org:create --definitionfile=config/project-scratch-def.json --setalias=scratch-org --setdefaultusername
            - name: Push source
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:source:push
            - name: Create user
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:user:create --definitionfile=config/user-def.json --setalias=new-user
            - name: Change password
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:user:password:generate --targetusername=new-user
            - name: Display user information
              id: display_user
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:user:display --targetusername=new-user --json
            - name: Display open url
              id: display_url
              uses: forcedotcom/salesforcedx-actions@master
              if: steps.check.outputs.isMatch == 'true'
              with:
                  args: force:org:open --urlonly --targetusername=new-user --json
    
