name: Starting a new work item

on:
    project_card:
        types: [moved]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check move from "TO DO" to "IN PROGRESS"
              if: steps.check.outputs.isMatch == 'true'
              shell: bash
              run: echo ${{ github.event.changes.column_id.from }} to ${{ github.event.project_card.column_id }}
            - name: Check out the source code
              uses: actions/checkout@v1
              if: steps.check.outputs.isMatch == 'true'
            - name: Populate auth file with SFDX_URL secret
              if: steps.check.outputs.isMatch == 'true'
              shell: bash
              run: echo Completed
